version: "3.7"

services:  
  go:
    image: golang
    volumes:
    - ./:/home/workspace
    # entrypoint: sleep infinity
    entrypoint: sh /home/workspace/goproject/run.sh && sleep infinity
    networks:
      - reverse_proxy_net
    ports:
      - '3000:3001'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - reverse_proxy_net

networks:
  reverse_proxy_net:
    name: reverse_proxy_net